# Generated by Django 4.2.6 on 2023-10-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='comments',
        ),
    ]
