# Generated by Django 4.2.6 on 2023-10-28 22:31

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='music_file',
            field=models.FileField(upload_to=core.models.get_upload_path, validators=[core.models.MusicFileValidator()]),
        ),
    ]
