# Generated by Django 4.2.6 on 2023-10-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playlistlike_timestamp_songlike_albumlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumlike',
            options={'verbose_name_plural': 'Album likes'},
        ),
        migrations.AlterModelOptions(
            name='playlistlike',
            options={'verbose_name_plural': 'Playlist likes'},
        ),
        migrations.AlterModelOptions(
            name='songlike',
            options={'verbose_name_plural': 'Song likes'},
        ),
        migrations.AddField(
            model_name='album',
            name='comments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='comments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
