# Generated by Django 4.2.6 on 2023-10-25 07:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_album_owner_alter_playlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=core.models.user_dir),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=core.models.user_dir),
        ),
    ]
